### ISSUE TITLE
Tracking issue for Custom Difficulty lints

### ISSUE THREAD

**Issue by jieyouxu** [jieyouxu/CDLint#1]
### Desirable Custom Difficulty lints

- [ ] Cyclic Enemy Descriptor `Base` references
- [ ] Undefined Enemy Descriptor references
- [ ] Unused Enemy Descriptors
- [ ] Invalid attributes
- [ ] Defunct attributes, e.g. `SeasonalEvents` or `UseSpawnRarity` modifiers(?)
- [ ] `min > max` in ranges
- [ ] Missing mandatory attributes, e.g. `min` or `max` in ranges
- [ ] Require either array of 4 elements `[T, T, T, T]` or single value `T`, but not array of different length or single value wrapped in array
