### ISSUE TITLE
Tracking issue for CDLint v0.2.* release series: a rewrite

### ISSUE THREAD

**Issue by jieyouxu** [jieyouxu/CDLint#8]
With the v0.1.* release series, I've gathered enough experience in dogfooding the CDLint tool to decide that it would need a rewrite because the v0.1.* series code was architecturally limiting to support features like lint levels and lint groups, as well as concerns like better error reporting and diagnostic output.

Here are the plans for the v0.2.* release series:

- [ ] Migrate general source code / JSON file slice based error reporting to use [`annotate-snippets-rs`](https://github.com/rust-lang/annotate-snippets-rs) , which makes it closer to `rustc`-style diagnostic output (which I like) :)
- [ ] Setup diagnostic infrastructure to separate concerns between diagnostic construction, report building and diagnostic emission.
- [ ] Investigate how to gracefully handle malformed JSON and suggest actionable fixes. Do we have to hand-roll a JSON parser? Probably, for better error reporting.
	- [ ] Hand-roll a lexer.
	- [ ] Hand-roll a LL(1) top-down recursive descent parser. We can use CSON grammar.
- [ ] Rework how lints are registered and organized. We want to support **lint levels** and **lint groups**:
	- We may want to make a distinction in how we handle early lints vs late lints.
	- We want the user to be able to override default lint levels via the command line and through a config file, with the command line taking priority (cli > config file > default lint levels).
- [ ] Try to recover as much as possible from "incorrect" CDs, we want to try to generate as much diagnostics as possible in one go, without the user having to repeatedly fix one thing, rerun the tool, and repeat.
- [ ] Add JSON formatting so this could also be used by the CD repo (easy: assuming our hand-rolled parser doesn't contain bugs, we just let serde_json parse the JSON and then pretty print it).
- [ ] Support diffing two Custom Difficulty JSONs.

## A hand-rolled JSON lexer and parser
I have surveyed the ecosystem for JSON parsers that provide good error messages, especially in context of users who do not have a programming background. I've come up empty. And thus, we're hand-rolling our own JSON lexer/parser, with inspiration probably from `rustc` yet again. Why? Because crates like `serde_json` are better at answering the "can this be parsed or not" and not at answering "why has the parsing failed"? We could certainly try parser combinator libraries `nom` and `nom-supreme` with error stacks and error trees. But then, is it really simpler than just rolling our own lexer/parser? I'm not entirely convinced. I don't care about *error recovery* per se, but I do want more contextual and *helpful* error messages.

I'm envisioning something like `rustc`'s parse errors:

```
error: this file contains an unclosed delimiter
 --> test.rs:4:3
  |
1 | fn main() {
  |           - unclosed delimiter
2 |     {
  |     - this delimiter might not be properly closed...
3 |         let foo = 0u8;
4 | }
  | - ^
  | |
  | ...as it matches this but it has different indentation
```

Errors like unpaired delimiters are *particularly common*. We should help the user out.

These hand-rolled lexers and parsers are going to need unit tests, and possibly ui tests like `rustc` (yet again) when they become more mature (probably too much hassle for our use case).

## Why so complicated?
It doesn't *need* to be as complex as the steps planned here. But I plan to use this project for future me to reference when I need to setup diagnostics infra etc. again.
